# Generated by Django 2.1.4 on 2018-12-20 18:38

import django.core.validators
from django.db import migrations, models
import fbscreen.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackInfoInputModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, validators=[django.core.validators.URLValidator()])),
                ('Number', models.CharField(blank=True, default=fbscreen.models.FeedbackInfoInputModel.random_string, max_length=100, unique=True)),
                ('description', models.TextField(max_length=500, verbose_name='Please describe accessibility problem')),
                ('content', models.CharField(blank=True, max_length=100, verbose_name='Please describe the content you need. For example, document name, or name of a video file.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Open', max_length=100)),
            ],
        ),
    ]
